### ISSUE TITLE
A couple things

### ISSUE THREAD

**Issue by tylercollier-devmtn** [DevMountain/angular-2-mini#1]
1. The following script tag is not mentioned in the instructions, but appears in the solution in the final step: `<script src="https://cdnjs.cloudflare.com/ajax/libs/angular-ui-router/1.0.3/angular-ui-router.js"></script>`
1. `homeCtrl` and `settingsCtrl` are referenced in Step 2, but the controllers themselves are not created. There is no code in those JS files, and those files are not included as `<script>` tags in `index.html`, so maybe better to take out the `controller` properties on the route config?

**Comment by devlemire** [comment]
I agree. Fixed.
